[package]
name = "sampler-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
sampler-layout.workspace = true
sampler-embed.workspace = true
sampler-similarity.workspace = true
sampler-audio.workspace = true
hound = "3.5.1"
tempfile.workspace = true
sampler-decode.workspace = true
sampler-analysis.workspace = true
serde_json.workspace = true
sampler-db.workspace = true
sampler-scan.workspace = true
thiserror.workspace = true
serde.workspace = true
memmap2 = "0.9.11"
regex = "1.13.1"
