[package]
name = "sampler-db"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
rusqlite.workspace = true
rusqlite_migration.workspace = true
thiserror.workspace = true
serde.workspace = true

[dev-dependencies]
tempfile.workspace = true
