[package]
name = "sampler-layout"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
sampler-similarity.workspace = true
thiserror.workspace = true
rayon = "1.12.0"
ndarray = "0.17"
umap-rs = "0.4.5"

[dev-dependencies]
tempfile.workspace = true
